apiVersion: v1
kind: Service
metadata:
  name: distributornetwork-service
spec:
  selector:
      appName: distributor-network
      version: "1.0"
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080